---
label: Application info
hide_body: true
fields:
- type: text
  name: link
  label: link
- type: text
  name: info_link_label
  label: info_link_label
- name: applications
  type: field_group_list
  fields:
  - name: heading
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: heading
  - name: label
    type: text
    config:
      required: false
    label: label
  - name: open
    type: boolean
    label: open
    default: false
  - name: closed_message
    type: text
    config:
      required: false
    label: closed_message
  - name: URL
    type: text
    config:
      required: false
    label: URL
  - name: color
    type: color
    label: color
    config:
      required: false
      color_format: Hex
  - name: open_date
    type: text
    config:
      required: false
    label: open date
  - name: close_date
    type: datetime
    label: close date
    description: ''
    config:
      required: false
      date_format: YYYY/MM/DD
      time_format: h:mm A ZZ
      display_utc: false
      export_format: YYYY-MM-DDThh:mm:ssZ
  - name: acceptance_date
    type: text
    config:
      required: false
    label: acceptance date
  config:
    min: 
    max: 
    labelField: 
  label: applications
- name: show_period
  type: boolean
  label: show application period
- type: text
  name: period_text
  label: period_text
- name: applications_open_date
  type: text
  config:
    required: false
  label: applications open date
- name: applications_close_date
  type: datetime
  label: applications close date
  description: ''
  config:
    required: false
    date_format: YYYY-MM-DD
    time_format: h:mm A ZZ
    display_utc: false
    export_format: YYYY-MM-DDThh:mm:ssZ
- name: acceptance_date
  type: text
  config:
    required: false
  label: acceptance date
- type: field_group
  name: target_applicants
  label: Target applicants
  fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: title
    label: title
  - type: textarea
    name: content
    label: content
  - type: text
    name: preamble
    label: preamble
  - type: field_group_list
    name: item
    label: item
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: icon
      label: icon
    - type: textarea
      name: content
      label: content
- type: field_group
  name: team
  label: Organisers
  fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: title
    label: title
  - type: field_group_list
    name: team_member
    label: team_member
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: designation
      label: designation
- type: field_group
  name: faq
  label: FAQ
  fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: title
    label: title
  - type: field_group_list
    name: item
    label: item
    fields:
    - type: text
      name: question
      label: question
    - name: icon
      type: text
      config:
        required: false
      label: icon
    - type: textarea
      name: answer
      label: answer
pages:
- data/application_info.yml
